version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: npm run dev
    environment:
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www
